add CheckPotentialFoldersFilesExclusions for local sources version
checkmarx-ts/CxUtils pull request #59
Opened 2023-02-27 18:16 UTC by pisatus

This script allows to check potential excludable files and folders, not only by naming patterns but also by the contents of the file itself. 
It searches files with comments such as "Copyright" or "Licensed" and suggests them as 3rd party.

2023-02-27 18:53 UTC, nleach999 commented
@pisatus please integrate the changes into the existing version of the script rather than forking it and renaming it.  I would suggest making deep inspection of the file contents an optional task considering it could take a significant amount of time to perform in some cases.

Maintaining two scripts with overlapping features is not really feasible in the long term.

2023-03-06 14:52 UTC, pisatus commented
> @pisatus please integrate the changes into the existing version of the script rather than forking it and renaming it. I would suggest making deep inspection of the file contents an optional task considering it could take a significant amount of time to perform in some cases.
> 
> Maintaining two scripts with overlapping features is not really feasible in the long term.

thanks for the review!
I made the changes accordingly! 
Please review

2023-03-27 13:23 UTC, nleach999 commented on CheckPotentialFoldersFilesExclusions/README.md
> +    For local storage usage also checkout https://checkmarx.atlassian.net/wiki/spaces/AA/pages/6825215196/Quick+Exclusions
Please remove links to private URLs.

2023-03-27 13:24 UTC, nleach999 requested changes
Looks good to merge, but please remove private links.

2023-03-27 16:05 UTC, pisatus commented on CheckPotentialFoldersFilesExclusions/README.md
> +    For local storage usage also checkout https://checkmarx.atlassian.net/wiki/spaces/AA/pages/6825215196/Quick+Exclusions
hi, removed the line in question!

2023-03-27 16:06 UTC, pisatus commented
Hi
I made the fixes suggested. 
thanks for all inputs!

2023-03-28 19:46 UTC, nleach999 approved these changes

2023-03-28 19:46 UTC, merged